=== Srestha2809/Password-Manager/PasswordManager/docs/JSON/account_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "title": "Describes an account object",

  "type": "object",
  "properties": {
    "description": {
      "type": "string",
      "description": "A description of the online account"
    },
    "userid": {
      "type": "string",
      "description": "User's identifier for logging-in"
    },
    "loginurl": {
      "type": [ "string", "null" ],
      "description": "Web address of the account's log-in page",
      "format": "uri"
    },
    "accountnum": {
      "type": "string",
      "description": "The account number for the user's online account"
    },
    "password": {
      "type": "object",
      "properties": {
        "value": {
          "type": "string",
          "description": "User's password for logging-in"
        },
        "strengthnum": {
          "type": "number",
          "description": "Indicates how secure the password is",
          "minimum": 0,
          "maximum": 100
        },
        "strengthtext": {
          "type": "string",
          "description": "Indicates how secure the password is",
          "enum": [ "very weak", "weak", "good", "strong", "very strong" ]
        },
        "lastreset": {
          "type": "string",
          "description": "Date the password was last updated"
        }
      },
      "required": [ "value", "strengthnum", "strengthtext" ]
    }
  },
  "required": ["description","userid","password"]
}

=== Srestha2809/Password-Manager/PasswordManager/docs/JSON/accounts.json
[

  {
    "description": "Newgrounds.com",
    "userid": "PeterParker",
    "loginurl": "https://www.newgrounds.com",
    "accountnum": "4589as095",
    "password": {
      "value": "nIeas4sadep",
      "strengthnum": 68,
      "strengthtext": "strong",
      "lastreset": "2022-05-31"
    }
  },
  {
    "description": "FanshaweOnline.ca",
    "userid": "mhughes39@fanshaweonline.ca",
    "loginurl": "https://www.fanshaweonline.ca",
    "accountnum": "0759313",
    "password": {
      "value": "new1pa55w0rd",
      "strengthnum": 93,
      "strengthtext": "very strong",
      "lastreset": "2022-05-31"
    }
  },
  {
    "description": "Facebook.com",
    "userid": "Srestha Bharadwaj",
    "loginurl": "https://www.facebook.com",
    "accountnum": "jdsa4034a",
    "password": {
      "value": "password101!",
      "strengthnum": 93,
      "strengthtext": "very strong",
      "lastreset": "2022-05-31"
    }
  },
  {
    "description": "Reddit.com",
    "userid": "SrB",
    "loginurl": "https://www.reddit.com",
    "accountnum": "545ada34",
    "password": {
      "value": "password200!",
      "strengthnum": 93,
      "strengthtext": "very strong",
      "lastreset": "2022-05-31"
    }
  }
]
